version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
     docker:
      - image: cimg/node:15.1
     steps:
      - checkout
      - node/install-packages
      - run: npm run test

workflows:
  sample:
    jobs:
      - test