version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test:
     docker:
      - image: cimg/node:15.1
     environment:
      NODE_ENV: ci
      PORT: 3000
     steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run test

workflows:
  sample:
    jobs:
      - build_and_test